name: leabra7-binder

channels:
  - cdg4
  - pytorch
  - conda-forge
  - default

dependencies:
  - leabra7>=0.0.14
  - matplotlib>=2.2.2
  - numpy>=1.14
  - pandas>=0.23
  - python=3.6.*
  - pytorch>=0.4
  - scipy>=1.1
